import { computed } from 'vue'
import { useSettingsStore } from '~/stores/settings'

const messages = {
  az: {
    lang_az: 'Azərbaycan',
    lang_ru: 'Rus',
    lang_en: 'İngilis',
    nav_home: 'Ana səhifə',
    nav_shop: 'Mağaza',
    nav_blog: 'Bloq',
    nav_about: 'Haqqımızda',
    nav_contact: 'Əlaqə',
    nav_faq: 'FAQ',
    nav_tracking: 'Sifariş izləmə',
    pages: 'Səhifələr',
    shop_department: 'Mağaza bölməsi',
    product_catalog: 'Məhsul kataloqu',
    mobile_language: 'Dil',
    mobile_menu: 'Menyu',
    mobile_categories: 'Kateqoriyalar',
    mobile_no_pages: 'Heç bir səhifə yoxdur',
    wishlist_label: 'Seçilmişlər',
    my_account_label: 'Hesabım',
    guest_label: 'Qonaq',
    cart_label: 'Səbət',
    availability: 'Mövcudluq',
    in_stock: 'Stokda var',
    out_of_stock: 'Stokda yoxdur',
    flash_sale: 'Flash Satış: 50%-ə qədər endirim!',
    not_found: 'Nəticə tapılmadı.',
    search_placeholder: 'Məhsul axtar...',
    cart_empty: 'Səbətiniz boşdur',
    total: 'Cəmi',
    cart_view: 'Səbətə bax',
    order_now: 'Sifariş et',
    continue_shopping: 'Alış-verişə davam et',
    cart_title: 'Alış-veriş Səbəti',
    cart_empty_title: 'Səbətiniz boşdur',
    cart_empty_desc: 'Görünür hələ heç bir məhsul əlavə etməmisiniz. Mağazamıza baxaraq ən son təklifləri kəşf edin.',
    back_to_shop: 'Mağazaya qayıt',
    order_summary: 'Sifarişin xülasəsi',
    subtotal: 'Məhsulların cəmi',
    shipping: 'Çatdırılma',
    free: 'Pulsuz',
    tax: 'Vergi (18%)',
    grand_total: 'Yekun Məbləğ',
    vat_included: 'ƏDV daxildir',
    coupon_code: 'Kupon kodu',
    apply: 'Tətbiq et',
    discount: 'Endirim',
    login: 'Giriş',
    logout: 'Çıxış',
    signup: 'Qeydiyyat',
    sign_in: 'Daxil ol',
    remember_me: 'Məni xatırla',
    forgot_password: 'Şifrəni unutmusunuz?',
    no_account: 'Hesabınız yoxdur?',
    signup_now: 'Qeydiyyatdan keçin',
    email: 'E-poçt',
    password: 'Şifrə',
    welcome_title: 'Xoş Gəlmisiniz!',
    login_subtitle: 'Hesabınıza daxil olun və alış-verişə başlayın.',
    email_placeholder: 'E-poçt ünvanınız',
    password_placeholder: 'Şifrəniz',
    profile: 'Profil',
    checkout_title: 'Sifariş',
    checkout_next: 'Sifarişə keç',
    checkout_finish: 'Sifarişi tamamla',
    sending: 'Göndərilir…',
    order_success: 'Sifarişiniz uğurla tamamlandı',
    required_fields: 'Zəhmət olmasa bütün məcburi xanaları doldurun.',
    cart_empty_short: 'Səbət boşdur.',
    order_failed: 'Sifariş yaradılmadı. Zəhmət olmasa yenidən yoxlayın.',
    settings_saved: 'Ayarlar yadda saxlanıldı',
    login_success: 'Giriş uğurludur',
    signup_success: 'Qeydiyyat uğurla tamamlandı',
    accept_terms: 'Zəhmət olmasa qaydaları qəbul edin.',
    image_upload_failed: 'Şəkil yüklənmədi',
    images_upload_failed: 'Şəkillər yüklənmədi',
    main_image_required: 'Əsas şəkil əlavə edin',
    product_code: 'Məhsulun kodu',
    category: 'Kateqoriya',
    tags: 'Taglar',
    sort: 'Sırala',
    sort_popularity: 'Populyarlıq',
    sort_price_asc: 'Qiymət: aşağıdan',
    sort_price_desc: 'Qiymət: yuxarıdan',
    sort_name_asc: 'Ad: A→Z',
    sort_name_desc: 'Ad: Z→A',
    all_categories: 'Bütün kateqoriyalar',
    categories: 'Kateqoriyalar',
    brands: 'Brendlər',
    price_range: 'Qiymət Aralığı',
    filter: 'Filtrlə',
    filters: 'Filtrlər',
    showing: 'Göstərilir',
    of: '/',
    results: 'nəticə',
    sold: 'Satıldı',
    sold_small: 'satıldı',
    sold_unit: 'ədəd',
    offer_ends_in: 'Təklif bitmə tarixi:',
    days: 'GÜNLƏR',
    hours: 'SAATLAR',
    mins: 'DƏQİQƏ',
    secs: 'SANİYƏ',
    limited_stock: 'Məhdud sayda',
    review: 'rəy',
    reviews: 'rəy',
    promo_strip: 'Pulsuz çatdırılma – 100 AZN üzəri sifarişlər üçün | Mağazadan pulsuz götürmə',
    follow_us: 'Bizi izləyin',
    footer_customer_services: 'Müştəri xidmətləri',
    footer_customer_support: 'Müştəri dəstəyi',
    footer_my_account: 'Hesabım',
    footer_quick_links: 'Sürətli keçidlər',
    footer_about_store: 'Mağaza haqqında',
    newsletter_title: 'Bülletenimizə abunə olun',
    newsletter_subtitle: 'Hər şənbə günü yeni endirim kuponu əldə edin.',
    subscribe: 'Abunə ol',
    newsletter_email_placeholder: 'E-poçt ünvanınızı daxil edin',
    shop_banner_cta: 'İndi bax',
    discover_now: 'İndi kəşf et',
    view_product: 'Məhsula bax',
    product_sold_out: 'Məhsul bitib',
    quick_add: 'Sürətli əlavə et',
    trust_score: 'Etibar xalı',
    verified: 'Təsdiqlənib',
    seller_role: 'Satıcı',
    products_label: 'Məhsul',
    orders_label: 'Sifariş',
    rating_label: 'Reytinq',
    view_store: 'Mağazaya bax',
    view_stores: 'Mağazalara bax',
    compare: 'Müqayisə et',
    compare_now: 'Müqayisəyə bax',
    compare_limit_reached: 'Müqayisə üçün maksimum məhsul sayı seçilib',
    clear_compare: 'Müqayisəni təmizlə',
    selected_filters: 'Aktiv filtrlər',
    results_count: 'nəticə',
    load_more: 'Daha çox göstər',
    browse_alternatives: 'Alternativlərə bax',
    no_results_suggestions: 'Oxşar kateqoriya və axtarış istiqamətləri',
    popular_searches_short: 'Populyar axtarışlar',
    clear_filters: 'Filterləri sıfırla',
    reset_filters: 'Sıfırla',
    pagination_prev: 'Geri',
    pagination_next: 'İrəli',
    notify_price_drop: 'Qiymət düşəndə xəbər ver',
    notify_restock: 'Stok qayıdanda xəbər ver',
    alert_email_label: 'E-poçt ünvanı',
    alert_submit: 'Bildiriş qur',
    alert_success: 'Bildiriş qeydə alındı',
    alert_price_drop_saved: 'Qiymət düşəndə sizə xəbər veriləcək',
    alert_restock_saved: 'Stok qayıdanda sizə xəbər veriləcək',
    top_sellers_short: 'Ən çox satılanlar',
    trend_now_short: 'Bu həftə trend',
    new_arrivals_short: 'Yeni gələnlər',
    new_badge: 'YENI',
    recently_viewed_short: 'Baxdıqlarınız',
    price_drops_short: 'Qiyməti düşənlər',
    top_rated_short: 'Ən yüksək qiymətləndirilənlər',
    category_landing: 'Kateqoriya vitrini',
    category_landing_subtitle: 'Bu kateqoriya üçün seçilmiş məhsullar, güclü filtr axını və daha ağıllı axtarış nəticələri göstərilir.',
    did_you_mean: 'Bunu nəzərdə tuturdunuz?',
    experience_builder: 'Təcrübə vitrini',
    new_customers: 'Yeni müştərilər',
    returning_customers: 'Qayıdan müştərilər',
    vip_layout: 'VIP düzən',
    verified_purchase: 'Təsdiqlənmiş alış',
    review_submit: 'Rəy göndər',
    loading: 'Yüklənir...',
    no_reviews_yet: 'Hələ rəy yoxdur.',
    min_label: 'Min',
    max_label: 'Max',
    attributes: 'Xüsusiyyətlər',
    tab_description: 'Təsvir',
    tab_additional: 'Əlavə məlumat',
    tab_reviews: 'Rəylər',
    buy_now: 'İndi al',
    add_to_cart: 'Səbətə at',
    added_to_cart: 'Məhsul səbətə əlavə olundu',
    compare_page_title: 'Müqayisə',
    compare_page_desc: 'Seçdiyiniz məhsulları burada yanaşı müqayisə edin.',
    compare_empty_title: 'Müqayisə siyahısı boşdur',
    compare_empty_desc: 'Məhsul kartındakı müqayisə düyməsi ilə 2-4 məhsul əlavə edin.',
    selected_short: 'Seçilən',
  },
  ru: {
    lang_az: 'Азербайджанский',
    lang_ru: 'Русский',
    lang_en: 'Английский',
    nav_home: 'Главная',
    nav_shop: 'Магазин',
    nav_blog: 'Блог',
    nav_about: 'О нас',
    nav_contact: 'Контакты',
    nav_faq: 'FAQ',
    nav_tracking: 'Отслеживание заказа',
    pages: 'Страницы',
    shop_department: 'Раздел магазина',
    product_catalog: 'Каталог товаров',
    mobile_language: 'Язык',
    mobile_menu: 'Меню',
    mobile_categories: 'Категории',
    mobile_no_pages: 'Нет страниц',
    wishlist_label: 'Избранное',
    my_account_label: 'Мой аккаунт',
    guest_label: 'Гость',
    cart_label: 'Корзина',
    availability: 'Наличие',
    in_stock: 'В наличии',
    out_of_stock: 'Нет в наличии',
    flash_sale: 'Flash Sale: скидки до 50%!',
    not_found: 'Ничего не найдено.',
    search_placeholder: 'Поиск товара...',
    cart_empty: 'Корзина пуста',
    total: 'Итого',
    cart_view: 'К корзине',
    order_now: 'Оформить заказ',
    continue_shopping: 'Продолжить покупки',
    cart_title: 'Корзина',
    cart_empty_title: 'Корзина пуста',
    cart_empty_desc: 'Похоже, вы ещё не добавили товары. Перейдите в магазин и выберите лучшие предложения.',
    back_to_shop: 'Вернуться в магазин',
    order_summary: 'Сводка заказа',
    subtotal: 'Сумма товаров',
    shipping: 'Доставка',
    free: 'Бесплатно',
    tax: 'Налог (18%)',
    grand_total: 'Итого',
    vat_included: 'НДС включён',
    coupon_code: 'Купон',
    apply: 'Применить',
    discount: 'Скидка',
    login: 'Войти',
    logout: 'Выйти',
    signup: 'Регистрация',
    sign_in: 'Войти',
    remember_me: 'Запомнить меня',
    forgot_password: 'Забыли пароль?',
    no_account: 'Нет аккаунта?',
    signup_now: 'Зарегистрироваться',
    email: 'Email',
    password: 'Пароль',
    welcome_title: 'Добро пожаловать!',
    login_subtitle: 'Войдите в аккаунт и начните покупки.',
    email_placeholder: 'Ваш email',
    password_placeholder: 'Ваш пароль',
    profile: 'Профиль',
    checkout_title: 'Заказ',
    checkout_next: 'К заказу',
    checkout_finish: 'Завершить заказ',
    sending: 'Отправляется…',
    order_success: 'Ваш заказ успешно оформлен',
    required_fields: 'Пожалуйста, заполните обязательные поля.',
    cart_empty_short: 'Корзина пуста.',
    order_failed: 'Не удалось создать заказ. Пожалуйста, попробуйте снова.',
    settings_saved: 'Настройки сохранены',
    login_success: 'Вход выполнен',
    signup_success: 'Регистрация завершена',
    accept_terms: 'Пожалуйста, примите условия.',
    image_upload_failed: 'Не удалось загрузить изображение',
    images_upload_failed: 'Не удалось загрузить изображения',
    main_image_required: 'Добавьте основное изображение',
    product_code: 'Код товара',
    category: 'Категория',
    tags: 'Теги',
    sort: 'Сортировка',
    sort_popularity: 'Популярность',
    sort_price_asc: 'Цена: по возрастанию',
    sort_price_desc: 'Цена: по убыванию',
    sort_name_asc: 'Название: A→Z',
    sort_name_desc: 'Название: Z→A',
    all_categories: 'Все категории',
    categories: 'Категории',
    brands: 'Бренды',
    price_range: 'Диапазон цены',
    filter: 'Фильтр',
    filters: 'Фильтры',
    showing: 'Показано',
    of: 'из',
    results: 'результатов',
    sold: 'Продано',
    sold_small: 'продано',
    sold_unit: 'шт.',
    offer_ends_in: 'Срок окончания:',
    days: 'ДНЕЙ',
    hours: 'ЧАСОВ',
    mins: 'МИН',
    secs: 'СЕК',
    limited_stock: 'Ограничено',
    review: 'отзыв',
    reviews: 'отзывов',
    promo_strip: 'Бесплатная доставка — для заказов от 100 AZN | Бесплатный самовывоз из магазина',
    follow_us: 'Мы в соцсетях',
    footer_customer_services: 'Сервис',
    footer_customer_support: 'Поддержка',
    footer_my_account: 'Мой аккаунт',
    footer_quick_links: 'Быстрые ссылки',
    footer_about_store: 'О магазине',
    newsletter_title: 'Подпишитесь на рассылку',
    newsletter_subtitle: 'Получайте новые купоны каждую субботу.',
    subscribe: 'Подписаться',
    newsletter_email_placeholder: 'Введите ваш email',
    shop_banner_cta: 'Смотреть',
    discover_now: 'Смотреть',
    view_product: 'Посмотреть товар',
    product_sold_out: 'Товар закончился',
    quick_add: 'Быстро в корзину',
    trust_score: 'Индекс доверия',
    verified: 'Проверен',
    seller_role: 'Продавец',
    products_label: 'Товары',
    orders_label: 'Заказы',
    rating_label: 'Рейтинг',
    view_store: 'Открыть магазин',
    view_stores: 'Открыть магазины',
    compare: 'Сравнить',
    compare_now: 'Открыть сравнение',
    compare_limit_reached: 'Достигнут максимальный лимит товаров для сравнения',
    clear_compare: 'Очистить сравнение',
    selected_filters: 'Активные фильтры',
    results_count: 'результат',
    load_more: 'Показать ещё',
    browse_alternatives: 'Смотреть альтернативы',
    no_results_suggestions: 'Похожие категории и поисковые направления',
    popular_searches_short: 'Популярные запросы',
    clear_filters: 'Сбросить фильтры',
    reset_filters: 'Сбросить',
    pagination_prev: 'Назад',
    pagination_next: 'Вперёд',
    notify_price_drop: 'Сообщить о снижении цены',
    notify_restock: 'Сообщить о появлении в наличии',
    alert_email_label: 'Email',
    alert_submit: 'Создать уведомление',
    alert_success: 'Уведомление сохранено',
    alert_price_drop_saved: 'Мы сообщим вам о снижении цены',
    alert_restock_saved: 'Мы сообщим вам, когда товар появится в наличии',
    top_sellers_short: 'Лидеры продаж',
    trend_now_short: 'Тренды недели',
    new_arrivals_short: 'Новые поступления',
    new_badge: 'НОВОЕ',
    recently_viewed_short: 'Вы смотрели',
    price_drops_short: 'Снижение цены',
    top_rated_short: 'Лучшие по рейтингу',
    category_landing: 'Витрина категории',
    category_landing_subtitle: 'Для этой категории показываются отобранные товары, удобные фильтры и более умные результаты поиска.',
    did_you_mean: 'Возможно, вы имели в виду?',
    experience_builder: 'Витрина сценария',
    new_customers: 'Новые покупатели',
    returning_customers: 'Постоянные покупатели',
    vip_layout: 'VIP витрина',
    verified_purchase: 'Подтверждённая покупка',
    review_submit: 'Отправить отзыв',
    loading: 'Загрузка...',
    no_reviews_yet: 'Пока нет отзывов.',
    min_label: 'Мин',
    max_label: 'Макс',
    attributes: 'Характеристики',
    tab_description: 'Описание',
    tab_additional: 'Доп. информация',
    tab_reviews: 'Отзывы',
    buy_now: 'Купить',
    add_to_cart: 'В корзину',
    added_to_cart: 'Товар добавлен в корзину',
    compare_page_title: 'Сравнение',
    compare_page_desc: 'Сравнивайте выбранные товары рядом друг с другом.',
    compare_empty_title: 'Список сравнения пуст',
    compare_empty_desc: 'Добавьте 2-4 товара через кнопку сравнения на карточке товара.',
    selected_short: 'Выбрано',
  },
  en: {
    lang_az: 'Azerbaijani',
    lang_ru: 'Russian',
    lang_en: 'English',
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_blog: 'Blog',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_faq: 'FAQ',
    nav_tracking: 'Order tracking',
    pages: 'Pages',
    shop_department: 'Shop department',
    product_catalog: 'Product catalog',
    mobile_language: 'Language',
    mobile_menu: 'Menu',
    mobile_categories: 'Categories',
    mobile_no_pages: 'No pages',
    wishlist_label: 'Favorites',
    my_account_label: 'My Account',
    guest_label: 'Guest',
    cart_label: 'Cart',
    availability: 'Availability',
    in_stock: 'In stock',
    out_of_stock: 'Out of stock',
    flash_sale: 'Flash sale: up to 50% off!',
    not_found: 'No results found.',
    search_placeholder: 'Search products...',
    cart_empty: 'Your cart is empty',
    total: 'Total',
    cart_view: 'View cart',
    order_now: 'Place order',
    continue_shopping: 'Continue shopping',
    cart_title: 'Shopping cart',
    cart_empty_title: 'Your cart is empty',
    cart_empty_desc: 'Looks like you haven’t added any items yet. Visit the shop to discover the latest deals.',
    back_to_shop: 'Back to shop',
    order_summary: 'Order summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    tax: 'Tax (18%)',
    grand_total: 'Total',
    vat_included: 'VAT included',
    coupon_code: 'Coupon code',
    apply: 'Apply',
    discount: 'Discount',
    login: 'Login',
    logout: 'Log out',
    signup: 'Sign up',
    sign_in: 'Sign in',
    remember_me: 'Remember me',
    forgot_password: 'Forgot password?',
    no_account: 'No account?',
    signup_now: 'Create account',
    email: 'Email',
    password: 'Password',
    welcome_title: 'Welcome!',
    login_subtitle: 'Sign in to your account and start shopping.',
    email_placeholder: 'Your email',
    password_placeholder: 'Your password',
    profile: 'Profile',
    checkout_title: 'Order',
    checkout_next: 'Continue',
    checkout_finish: 'Complete order',
    sending: 'Sending…',
    order_success: 'Your order was placed successfully',
    required_fields: 'Please fill in all required fields.',
    cart_empty_short: 'Your cart is empty.',
    order_failed: 'Could not create the order. Please try again.',
    settings_saved: 'Settings saved',
    login_success: 'Logged in',
    signup_success: 'Signed up successfully',
    accept_terms: 'Please accept the terms.',
    image_upload_failed: 'Image upload failed',
    images_upload_failed: 'Image uploads failed',
    main_image_required: 'Add a main image',
    product_code: 'Product code',
    category: 'Category',
    tags: 'Tags',
    sort: 'Sort',
    sort_popularity: 'Popularity',
    sort_price_asc: 'Price: low to high',
    sort_price_desc: 'Price: high to low',
    sort_name_asc: 'Name: A→Z',
    sort_name_desc: 'Name: Z→A',
    all_categories: 'All categories',
    categories: 'Categories',
    brands: 'Brands',
    price_range: 'Price range',
    filter: 'Filter',
    filters: 'Filters',
    showing: 'Showing',
    of: 'of',
    results: 'results',
    sold: 'Sold',
    sold_small: 'sold',
    sold_unit: '',
    offer_ends_in: 'Offer ends in:',
    days: 'DAYS',
    hours: 'HOURS',
    mins: 'MINS',
    secs: 'SECS',
    limited_stock: 'Limited stock',
    review: 'review',
    reviews: 'reviews',
    promo_strip: 'Free delivery — for orders over 100 AZN | Free store pickup',
    follow_us: 'Follow us',
    footer_customer_services: 'Customer services',
    footer_customer_support: 'Support',
    footer_my_account: 'My account',
    footer_quick_links: 'Quick links',
    footer_about_store: 'About the store',
    newsletter_title: 'Subscribe to our newsletter',
    newsletter_subtitle: 'Get a new coupon every Saturday.',
    subscribe: 'Subscribe',
    newsletter_email_placeholder: 'Enter your email',
    shop_banner_cta: 'Shop now',
    discover_now: 'Discover now',
    view_product: 'View product',
    product_sold_out: 'Sold out',
    quick_add: 'Quick add',
    trust_score: 'Trust score',
    verified: 'Verified',
    seller_role: 'Seller',
    products_label: 'Products',
    orders_label: 'Orders',
    rating_label: 'Rating',
    view_store: 'View store',
    view_stores: 'View stores',
    compare: 'Compare',
    compare_now: 'Open compare',
    compare_limit_reached: 'You reached the maximum compare limit',
    clear_compare: 'Clear compare',
    selected_filters: 'Active filters',
    results_count: 'results',
    load_more: 'Load more',
    browse_alternatives: 'Browse alternatives',
    no_results_suggestions: 'Nearby categories and search directions',
    popular_searches_short: 'Popular searches',
    clear_filters: 'Clear filters',
    reset_filters: 'Reset',
    pagination_prev: 'Back',
    pagination_next: 'Next',
    notify_price_drop: 'Notify on price drop',
    notify_restock: 'Notify on restock',
    alert_email_label: 'Email',
    alert_submit: 'Create alert',
    alert_success: 'Alert saved',
    alert_price_drop_saved: 'We will notify you when the price drops',
    alert_restock_saved: 'We will notify you when the item is back in stock',
    top_sellers_short: 'Top sellers',
    trend_now_short: 'Trending this week',
    new_arrivals_short: 'New arrivals',
    new_badge: 'NEW',
    recently_viewed_short: 'Recently viewed',
    price_drops_short: 'Price drops',
    top_rated_short: 'Top rated',
    category_landing: 'Category landing',
    category_landing_subtitle: 'This category highlights curated products, stronger filters and smarter search results.',
    did_you_mean: 'Did you mean',
    experience_builder: 'Experience builder',
    new_customers: 'New customers',
    returning_customers: 'Returning customers',
    vip_layout: 'VIP layout',
    verified_purchase: 'Təsdiqlənmiş alış',
    review_submit: 'Submit review',
    loading: 'Loading...',
    no_reviews_yet: 'No reviews yet.',
    min_label: 'Min',
    max_label: 'Max',
    attributes: 'Attributes',
    tab_description: 'Description',
    tab_additional: 'Additional information',
    tab_reviews: 'Reviews',
    buy_now: 'Buy now',
    add_to_cart: 'Add to cart',
    added_to_cart: 'Added to cart',
    compare_page_title: 'Compare',
    compare_page_desc: 'Review your selected products side by side.',
    compare_empty_title: 'Your compare list is empty',
    compare_empty_desc: 'Use the compare button on product cards to add 2-4 products.',
    selected_short: 'Selected',
  }
} as const

export type LangCode = keyof typeof messages
export type TKey = keyof (typeof messages)['az']

export const useT = () => {
  const settingsStore = useSettingsStore()
  const lang = computed<LangCode>(() => {
    const raw = (settingsStore.settings as any).language
    return raw === 'ru' || raw === 'en' ? raw : 'az'
  })

  const t = (key: TKey) => {
    return (messages[lang.value] as any)[key] || messages.az[key] || String(key)
  }

  return { t, lang }
}
